FIRST_LAUNCH = 'Un utilisateur de l\'équipe Management va être créé\nafin de pouvoir continuer'
NO_CLIENT_WITHOUT_EVENT = 'Pas de client avec contrat sans évènement'
BAD_EMAIL = 'Votre saisie ne correspond pas à une adresse mail.'
BAD_EMPLOYEE_NUMBER = 'Votre saisie ne correspond pas à un numéro d\'employé.'
BAD_DEPARTMENT = 'Votre saisie ne correspond pas à un département.'
SELECT_USER_FAILED = 'Ce numéro ne correspond pas à un utilisateur.'
BAD_SELECT_USER = 'Merci d\'entrer un nombre'
BAD_SELECT_CLIENT = 'Merci d\'entrer un nombre'
BAD_TOTAL_AMOUNT = 'Merci d\'entrer un nombre'
BAD_REST_AMOUNT = 'Merci d\'entrer un nombre'
BAD_SELECT_CONTRACT = 'Merci d\'entrer un nombre'
SELECT_CLIENT_FAILED = 'Ce numéro ne correspond pas à un client.'
SELECT_CONTRACT_FAILED = 'Ce numéro ne correspond pas à un contrat.'
BAD_PHONE = 'Numéro de téléphone incorrect'
UNKNOWN = 'Cette commande est inconnue'
MAIN_MENU = ('Merci d\'entrer la commande correspondant à ce que vous souhaitez faire\n\n'
             'Entrer "HELP" pour avoir la description des commandes\n'
             'Entrer "EXIT" pour quitter l\'application')
HELP = ('Liste des actions possibles :\n '
        'ADD | UPDATE | VIEW | DELETE\n\n '
        'Liste des catégories possibles :\n '
        'USER | CLIENT | CONTRACT | EVENT\n\n '
        'Syntaxe : ACTION CATEGORIE\n\n'
        'L\'accès à certaines actions est restreint en fonction des permissions'
        ' attribuées à votre département.\n\n'
        'Pour les connaître taper PERMISSION')
LOGIN_FAILED = 'Vos identifiants sont inconnus\nL\'application va s\'arrêter'
PASSWORD_FIRST_TIME = 'Bienvenue pour votre première connexion.\n\nVeuillez définir votre mot de passe'
PASSWORD_SECOND_TIME = ('Bienvenue pour votre première connexion.\n\n'
                        'Veuillez entrer une deuxième fois votre mot de passe')
PASSWORD_MATCH_FAILED = 'Les mots de passe ne sont pas identiques'
BAD_CONTRACT_STATUS = 'Cette réponse n\'est pas possible.\n\nMerci d\'indiquer y or n comme demandé'
PASSWORD_EMPTY = 'Votre mot de passe ne peut pas être vide.'
BAD_TOKEN = 'Vous avez été déconnecté, merci de vous reconnecter.'
