NORMAL = {
    'ADD_CLIENT': 'Ajout d\'un client',
    'ADD_CONTRACT': 'Ajout d\'un contrat',
    'ADD_EVENT': 'Ajout d\'un évènement',
    'ADD_USER': 'Ajout d\'un utilisateur',
    'CONNECTION': 'Connexion',
    'DELETE_USER': 'Suppression d\'un utilisateur',
    'DELETE_CLIENT': 'Suppression d\'un client',
    'DELETE_CONTRACT': 'Suppression d\'un contrat',
    'DELETE_EVENT': 'Suppression d\'un évènement',
    'EXIT': 'Au revoir',
    'FILTER': 'Aide pour les filtres',
    'FIRST_LAUNCH': 'Premier lancement de l\'application',
    'HELP': 'Aide',
    'NO_CLIENT': 'Aucun client n\'est enregistré',
    'NO_CONTRACT': 'Cette action sur les contrats n\'est pas possible pour le moment',
    'NO_EVENT': 'Cette action sur les évènements n\'est pas possible pour le moment',
    'MAIN_MENU': 'Menu principal',
    'PASSWORD': 'Définition du mot de passe',
    'PERMISSION': 'Tableau des permissions',
    'SELECT_USER': 'Sélection d\'un utilisateur',
    'SELECT_USER_FOR_DELETE': 'Sélection d\'un utilisateur',
    'SELECT_CLIENT': 'Selection d\'un client',
    'SELECT_CLIENT_WITH_EVENT': 'Selection d\'un client',
    'SELECT_CLIENT_WITHOUT_EVENT': 'Selection d\'un client',
    'SELECT_CLIENT_WITH_CONTRACT': 'Selection d\'un client',
    'SELECT_CONTRACT': 'Selection d\'un contrat',
    'SELECT_CONTRACT_WITH_EVENT': 'Selection d\'un contrat',
    'SELECT_CONTRACT_WITHOUT_EVENT': 'Selection d\'un contrat',
    'UPDATE_USER': 'Mise à jour d\'un utilisateur',
    'UPDATE_CLIENT': 'Mise à jour d\'un client',
    'UPDATE_CONTRACT': 'Mise à jour d\'un contrat',
    'UPDATE_EVENT': 'Mise à jour d\'un évènement',
    'VIEW_USER': 'Informations sur l\'utilisateur',
    'VIEW_USERS': 'Informations sur les utilisateurs',
    'VIEW_CLIENT': 'Informations sur le client',
    'VIEW_CLIENTS': 'Informations sur les clients',
    'VIEW_CONTRACT': 'Informations sur le contrat',
    'VIEW_CONTRACTS': 'Informations sur les contrats',
    'VIEW_EVENT': 'Informations sur l\'évènement',
    'VIEW_EVENTS': 'Informations sur les évènements',
}

ERROR = {
    'ADD_USER': 'Création de l\'utilisateur impossible',
    'ADD_CONTRACT': 'Création du contrat impossible',
    'ERROR': 'Erreur de saisie',
    'TOKEN': 'Déconnexion automatique',
    'FORBIDDEN': 'Vous n\'êtes pas autorisé à faire cette action',
}

GOOD = {
    'ADD_USER': 'Utilisateur créé',
    'ADD_CLIENT': 'Client ajouté',
    'ADD_CONTRACT': 'Contrat ajouté',
    'ADD_EVENT': 'Evènement ajouté',
    'UPDATE_USER': 'Utilisateur mis à jour',
    'UPDATE_CLIENT': 'Client mis à jour',
    'UPDATE_CONTRACT': 'Contrat mis à jour',
    'UPDATE_EVENT': 'Evènement mis à jour',
    'DELETE_USER': 'Utilisateur supprimé',
    'DELETE_CLIENT': 'Client supprimé',
    'DELETE_CONTRACT': 'Contrat supprimé',
    'DELETE_EVENT': 'Evènement supprimé',
    'CONNECTION': '[green]Connexion réussie[/green]'
}

FAILED = {
    'ADD': 'Ajout annulé',
    'STOPPED': 'Ajout annulé',
    'UPDATE': 'Mise à jour annulée',
    'DELETE': 'Suppression annulée',
    'ERROR': 'Erreur de saisie',
    'CONNECTION': 'Erreur de connexion'
}
