NORMAL = {
    'FIRST_LAUNCH': 'Premier lancement de l\'application',
    'ADD_USER': 'Ajout d\'un utilisateur',
    'UPDATE_USER': 'Mise à jour d\'un utilisateur',
    'VIEW_USER': 'Informations sur l\'utilisateur',
    'DELETE_USER': 'Suppression d\'un utilisateur',
    'SELECT_USER': 'Sélection d\'un utilisateur',
    'SELECT_USER_FOR_DELETE': 'Sélection d\'un utilisateur',
    'SELECT_SUPPORT_USER': 'Selection d\'un utilisateur support',
    'ADD_CLIENT': 'Ajout d\'un client',
    'UPDATE_CLIENT': 'Mise à jour d\'un client',
    'DELETE_CLIENT': 'Suppression d\'un client',
    'SELECT_CLIENT': 'Selection d\'un client',
    'SELECT_CLIENT_WITH_EVENT': 'Selection d\'un client',
    'SELECT_CLIENT_WITHOUT_EVENT': 'Selection d\'un client',
    'SELECT_CLIENT_WITH_CONTRACT': 'Selection d\'un client',
    'VIEW_CLIENT': 'Informations sur le client',
    'NO_CLIENT': 'Aucun client n\'est enregistré',
    'ADD_CONTRACT': 'Ajout d\'un contrat',
    'UPDATE_CONTRACT': 'Mise à jour d\'un contrat',
    'DELETE_CONTRACT': 'Suppression d\'un contrat',
    'SELECT_CONTRACT': 'Selection d\'un contrat',
    'SELECT_CONTRACT_WITH_EVENT': 'Selection d\'un contrat',
    'SELECT_CONTRACT_WITHOUT_EVENT': 'Selection d\'un contrat',
    'VIEW_CONTRACT': 'Informations sur le contrat',
    'NO_CONTRACT': 'Aucun contrat n\'est enregistré',
    'ADD_EVENT': 'Ajout d\'un évènement',
    'UPDATE_EVENT': 'Mise à jour d\'un évènement',
    'DELETE_EVENT': 'Suppression d\'un évènement',
    'VIEW_EVENT': 'Informations sur l\'évènement',
    'NO_EVENT': 'Aucun évènement n\'est enregistré',
    'CONNECTION': 'Connexion',
    'PERMISSION': 'Tableau des permissions',
    'HELP': 'Aide',
    'EXIT': 'Au revoir',
    'MAIN_MENU': 'Menu principal',
    'PASSWORD': 'Définition du mot de passe',
}

ERROR = {
    'ADD_USER': 'Création d\'utilisateur annulé',
    'UNKNOWN': 'Erreur de saisie',
    'SELECT_CONTRACT': 'Erreur de saisie',
    'EMPLOYEE_NUMBER': 'Erreur de saisie',
    'SELECT_USER': 'Erreur de saisie',
    'PHONE': 'Erreur de saisie',
    'TOTAL_AMOUNT': 'Erreur de saisie',
    'REST_AMOUNT': 'Erreur de saisie',
    'DATE_START': 'Erreur de saisie',
    'DATE_STOP': 'Erreur de saisie',
    'PASSWORD': 'Erreur de saisie',
    'SELECT_CONTRACT': 'Erreur de saisie',
    'SELECT_CLIENT': 'Erreur de saisie',
    'CONTRACT_STATUS': 'Erreur de saisie',
    'DEPARTMENT': 'Erreur de saisie',
    'TOKEN': 'Déconnexion automatique',
    'FORBIDDEN': 'Vous n\'êtes pas autorisé à faire cette action',
}

GOOD = {
    'ADD_USER': 'Utilisateur créé',
    'UPDATE_USER': 'Utilisateur mis à jour',
    'DELETE_USER': 'Utilisateur supprimé',
    'ADD_CLIENT': 'Client ajouté',
    'UPDATE_CLIENT': 'Client mis à jour',
    'DELETE_CLIENT': 'Client supprimé',
    'ADD_CONTRACT': 'Contrat ajouté',
    'UPDATE_CONTRACT': 'Contrat mis à jour',
    'DELETE_CONTRACT': 'Contrat supprimé',
    'ADD_EVENT': 'Evènement ajouté',
    'UPDATE_EVENT': 'Evènement mis à jour',
    'DELETE_EVENT': 'Evènement supprimé',
    'CONNECTION': '[green]Connexion réussie[/green]'
}

FAILED = {
    'UPDATE_USER': 'Utilisateur non mis à jour',
    'ADD_CLIENT': 'Impossible d\'ajouter le client',
    'ADD_CONTRACT': '*impossible d\'ajouter le contrat',
    'DELETE_CONTRACT': 'Contrat non supprimé',
    'UPDATE_CLIENT': 'Client non mis à jour',
    'ADD_EVENT': 'Evènement non ajouté',
    'UPDATE_EVENT': 'Evènement non mis à jour',
    'DELETE_EVENT': 'Evènement non supprimé',
    'ADD_USER': 'Impossible d\'enregistrer l\'utilisateur',
    'CONNECTION': 'Erreur de connexion',
    'SELECT_USER': 'Erreur de saisie',
    'SELECT_CLIENT': 'Erreur de saisie',
    'PASSWORD': 'Erreur de saisie',
    'EMAIL': 'Erreur de saisie',
}
